<?php
    setcookie("fortune_message","", time()+60*60*24*365);

    $_COOKIE['fortune_message'] = array(
        1=>"A beautiful, smart, and loving person will be coming into your life.",
        2=>"A dubious friend may be an enemy in camouflage.",
        3=>"A faithful friend is a strong defense.",
        4=>"A feather in the hand is better than a bird in the air.",
        5=>"A fresh start will put you on your way",
        6=>"A friend asks only for your time not your money",
        7=>"A friend is a present you give yourself.",
        8=>"A gambler not only will lose what he has, but also will lose what he doesn’t have",
        9=>"A golden egg of opportunity falls into your lap this month",
        10=>"A good friendship is often more important than a passionate romance.",
        11=>"A good time to finish up old tasks",
        12=>"A hunch is creativity trying to tell you something.",
        13=>"A lifetime friend shall soon be made.",
        14=>"A lifetime of happiness lies ahead of you.",
        15=>"A light heart carries you through all the hard times.",
        16=>"A new perspective will come with the new year.",
        17=>"A person is never to (sic) old to learn",
        18=>"A person of words and not deeds is like a garden full of weeds.",
        19=>"A pleasant surprise is waiting for you.",
        20=>"A short pencil is usually better than a long memory any day.",
        21=>"A small donation is call for. It’s the right thing to do.",
        22=>"A smile is your personal welcome mat.",
        23=>"A smooth long journey! Great expectations",
        24=>"A soft voice may be awfully persuasive",
        25=>"A truly rich life contains love and art in abundance",
        26=>"Accept something that you cannot change, and you will feel better",
        27=>"Adventure can be real happiness",
        28=>"Advice is like kissing. It costs nothing and is a pleasant thing to do",
        29=>"Advice, when most needed, is least heeded",
        30=>"All the effort you are making will ultimately pay off",
        31=>"All the troubles you have will pass away very quickly",
        32=>"All will go well with your new project",
        33=>"All your hard work will soon pay off",
        34=>"Allow compassion to guide your decisions",
        35=>"An acquaintance of the past will affect you in the near future",
        36=>"An agreeable romance might begin to take on the appearance",
        37=>"An important person will offer you support",
        38=>"An inch of time is an inch of gold",
        39=>"Any day above ground is a good day",
        40=>"Any decision you have to make tomorrow is a good decision",
        41=>"At the touch of love, everyone becomes a poet",
        42=>"Be careful or you could fall for some tricks today",
        43=>"Beauty in its various forms appeals to you",
        44=>"Because you demand more from yourself, others respect you deeply",
        45=>"Believe in yourself and others will too",
        46=>"Believe it can be done",
        47=>"Better ask twice than lose yourself once",
        48=>"Chance favors those in motion",
        49=>"Carve your name on your heart and not on marble", 
        50=>"Bide your time, for success is near"
    );
?>